# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1olgV7WH4bTPBucn9hiRAfxywSxpuacf2
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score



"""Data collection and preprocessing

"""

#loading the data from csv file to a pandas Dataframe
raw_mail_data = pd.read_csv('/content/mail_data.csv')

mail_data= raw_mail_data.where(pd.notnull(raw_mail_data))

#printing the first 5 rows
mail_data.head()

#checking the rows and collumns in the data frame
mail_data.shape



"""label Ecoding"""

#separating the data as texts and label
X= mail_data['Message']
Y= mail_data['Category']

print(X)

print(Y)



"""Train test split"""

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=3)

