# -*- coding: utf-8 -*-
"""matrix operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1VZNLaF_0L6eDSuHUaMlbKwC4VqstPt
"""

import numpy as np



"""matrix addition"""

#creating 2 matrices
A=np.array([[2,3],[4,5]])

B=np.array([[6,7],[8,9]])

print(A)

print(B)

A.shape

B.shape

sum=A+B
print(sum)

#creating 2 matrices with random values
matrix_1=np.random.randint(10, size=(3,3))
matrix_2=np.random.randint(20, size=(3,3))

print(matrix_1)

print(matrix_2)

sum=matrix_1+matrix_2
print(sum)



sum_2=np.add(matrix_1,matrix_2)

print(sum_2)



"""Difference of matrices"""

matrix_1=np.random.randint(10, size=(5,5))
matrix_2=np.random.randint(30,size=(5,5))

print(matrix_1)

print(matrix_2)

difference=matrix_1-matrix_2
print(difference)

diff=np.subtract(matrix_1,matrix_2)
print(diff)



"""Multiplying a matrix with a scalar"""

x=5
y=np.random.randint(10, size=(5,5))

product=np.dot(x,y)
print(product)

product.shape

