# -*- coding: utf-8 -*-
"""Vector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MC6Dc3r7lHaU82KqKevUaJT-ukm6ISHy
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()



"""Plotting a vector"""

plt.quiver(0,0,4,5)
plt.show()

plt.quiver(0,0,4,5, scale_units='xy', angles='xy',scale=1)
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

plt.quiver(0,0,4,5, scale_units='xy', angles='xy',scale=1, color='b')
plt.quiver(0,0,-3,-6, scale_units='xy', angles='xy',scale=1, color='y')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()



"""Addition of two vectors"""

vector_1=np.asarray([0,0,2,3])
vector_2=np.asarray([0,0,3,-2])
sum = vector_1  + vector_2
print(sum)

plt.quiver(0,0,4,5, scale_units='xy', angles='xy',scale=1, color='b')
plt.quiver(0,0,-3,-6, scale_units='xy', angles='xy',scale=1, color='y')
plt.quiver(0,0,5,1, scale_units='xy', angles='xy',scale=1, color='r')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()



"""Multiplying a vector by a scalar"""

vector_1 = np.asarray([0,0,2,3])
vector_2=2*vector_1
print(vector_2)

plt.quiver(0,0,2,3, scale_units='xy', angles='xy',scale=1, color='b')
plt.quiver(0,0,4,6, scale_units='xy', angles='xy',scale=1, color='y')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

import numpy as np

"""vector operations-

"""

#dot product of 2 vectors

a=np.array([2,3])

b=np.array([4,4])

a_dot_b=np.dot(a,b)
print(a_dot_b)

c=np.array([40,20,35])

d=np.array([18,32,50])

c_cross_d=np.cross(c,d)
print(c_cross_d)



"""projection of "a" vector on "v" vector"""

a=np.array([2,5])

v=np.array([8,-6])

#magnitude of "v" vector
magnitude_of_v=np.sqrt(sum(v**2))

proj_of_a_on_v=(np.dot(a,v)/magnitude_of_v**2)*v

print('projection of a vector on v vector=', proj_of_a_on_v)

